# Generated by Django 5.0.4 on 2024-04-19 16:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bot', '0005_telegrampost'),
    ]

    operations = [
        migrations.RenameField(
            model_name='telegrampost',
            old_name='chat_id',
            new_name='message_id',
        ),
    ]
